In [37]:
import pandas as pd

In [38]:
year=2022
lga_df = pd.read_csv("Anambra_LGAs.csv")
df = pd.read_excel("Geography & Population.xlsx", sheet_name="T5")
df.head()

,LGA,2006 MALE,2006 FEMALE,2006 TOTAL,2022 MALE,2022 FEMALE,2022 TOTAL
0,AGUATA,187262,182710,369972,309974,302439,612412
1,ANAMBRA EAST,77539,74610,152149,128350,123501,251851
2,ANAMBRA WEST,85833,81470,167303,142079,134857,276936
3,ANAOCHA,142961,141254,284215,236642,233817,470459
4,AWKA NORTH,57219,54973,112192,94714,90996,185711

In [39]:
columns = ['lga_id', 'year', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)


for index, row in df.iterrows():
    
    # if(lga_df.loc[lga_df['lga_name'] == row['LGA'], 'lga_id'].values[0]):
    #     print(row["LGA"], lga_df["lga_name"])
    # else:
    transformed_data = [{
        'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
        'year': year,
        'gender': 'Male',
        'population': row[f"{year} MALE"],
    },{
        'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
        'year': year,
        'gender': 'Female',
        'population': row[f"{year} FEMALE"],
    }]   

    new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id  year  gender population
0      13  2022    Male     309974
1      13  2022  Female     302439
2      18  2022    Male     128350
3      18  2022  Female     123501
4       2  2022    Male     142079
5       2  2022  Female     134857
6       9  2022    Male     236642
7       9  2022  Female     233817
8      15  2022    Male      94714
9      15  2022  Female      90996
10     20  2022    Male     160401
11     20  2022  Female     153532
12      6  2022    Male     134186
13      6  2022  Female     127602
14     12  2022    Male      81897
15     12  2022  Female      77867
16     17  2022    Male     132511
17     17  2022  Female     129735
18      8  2022    Male     362879
19      8  2022  Female     350561
20      3  2022    Male     175180
21      3  2022  Female     167162

In [40]:
new_df["year"]=new_df["year"].astype(int)
new_df["population"]=new_df["population"].astype(int)
new_df["lga_id"]=new_df["lga_id"].astype(int)

In [41]:
new_df.to_csv(f"{year}_Anambra_population.csv", index=False)
print(f"{year} Done With this Shit!")

2022 Done With this Shit!