In [19]:
import pandas as pd

In [20]:
pry_df = pd.read_csv("Primary_Schools.csv")
pry_df.head()

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,2001,CENTRAL SCHOOL ACHINA,PUBLIC MISSION,Primary,NaN,NaN
1,13,2002,PRIMARY SCHOOL EKE ACHINA,PUBLIC MISSION,Primary,NaN,NaN
2,13,2003,OBINIKPA SCHOOL ACHINA,PUBLIC MISSION,Primary,NaN,NaN
3,13,2004,PROGRESSIVE SCHOOL ACHINA,PUBLIC MISSION,Primary,NaN,NaN
4,13,2005,CENTRAL SCHOOL AGULUEZECHUKWU,PUBLIC MISSION,Primary,NaN,NaN

In [21]:
sec_df = pd.read_csv("Secondary_Schools.csv")
sec_df.head()

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,1,AGUATA HIGH SCH.AGUATA,PUBLIC,Secondary,NaN,NaN
1,13,2,CHRIST THE REDEEMER COLLEGE AMESI,PUBLIC,Secondary,NaN,NaN
2,13,3,COMM SEC. SCH. (BSS) EZINIFITE,PUBLIC,Secondary,NaN,NaN
3,13,4,COMM SEC. SCH. (BSS) IGBOUKWU,PUBLIC,Secondary,NaN,NaN
4,13,5,COMM SEC. SCH. AGULUEZECHUKWU,PUBLIC,Secondary,NaN,NaN

In [22]:
new_df = pd.concat([sec_df, pry_df], ignore_index=True)
new_df.head(1500)

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,1,AGUATA HIGH SCH.AGUATA,PUBLIC,Secondary,NaN,NaN
1,13,2,CHRIST THE REDEEMER COLLEGE AMESI,PUBLIC,Secondary,NaN,NaN
2,13,3,COMM SEC. SCH. (BSS) EZINIFITE,PUBLIC,Secondary,NaN,NaN
3,13,4,COMM SEC. SCH. (BSS) IGBOUKWU,PUBLIC,Secondary,NaN,NaN
4,13,5,COMM SEC. SCH. AGULUEZECHUKWU,PUBLIC,Secondary,NaN,NaN
...,...,...,...,...,...,...,...
1495,8,2460,CHUKE MEMORIAL . PRIMARY OBOSI,PUBLIC MISSION,Primary,NaN,NaN
1496,8,2461,OKPUNO UMUOTA PRIMARY SXCHOOLOBOSI,PUBLIC,Primary,NaN,NaN
1497,8,2462,GBUGHOBI MEMORIAL . CENTRAL . SCHOOL. OBOSI,PUBLIC,Primary,NaN,NaN
1498,8,2463,COMMUNITY PRIMARY UGAMUMA OBOS,PUBLIC MISSION,Primary,NaN,NaN
1499,8,2464,IRE CENTRAL SCHOOL OBOSI,PUBLIC MISSION,Primary,NaN,NaN

In [23]:
new_df.head(1500)

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,1,AGUATA HIGH SCH.AGUATA,PUBLIC,Secondary,NaN,NaN
1,13,2,CHRIST THE REDEEMER COLLEGE AMESI,PUBLIC,Secondary,NaN,NaN
2,13,3,COMM SEC. SCH. (BSS) EZINIFITE,PUBLIC,Secondary,NaN,NaN
3,13,4,COMM SEC. SCH. (BSS) IGBOUKWU,PUBLIC,Secondary,NaN,NaN
4,13,5,COMM SEC. SCH. AGULUEZECHUKWU,PUBLIC,Secondary,NaN,NaN
...,...,...,...,...,...,...,...
1495,8,2460,CHUKE MEMORIAL . PRIMARY OBOSI,PUBLIC MISSION,Primary,NaN,NaN
1496,8,2461,OKPUNO UMUOTA PRIMARY SXCHOOLOBOSI,PUBLIC,Primary,NaN,NaN
1497,8,2462,GBUGHOBI MEMORIAL . CENTRAL . SCHOOL. OBOSI,PUBLIC,Primary,NaN,NaN
1498,8,2463,COMMUNITY PRIMARY UGAMUMA OBOS,PUBLIC MISSION,Primary,NaN,NaN
1499,8,2464,IRE CENTRAL SCHOOL OBOSI,PUBLIC MISSION,Primary,NaN,NaN

In [24]:
new_df.to_csv("combine_schools.csv", index=False)
print("Done!")

Done!