In [32]:
import pandas as pd

In [33]:
timestamp="01-01-2023"
df= pd.read_excel("primary_school.xlsx")
df.head()

,S/N,LGA,SCHOOL_TYPE,SCHOOL,ECCDE1_M,ECCDE1_F,ECCDE2_M,ECCDE2_F,ECCDE3_M,ECCDE3_F,...,PRY5_F,PRY6_M,PRY6_F,PRY_M,PRY_F,PRY_T,TOTAL,TEACHER_M,TEACHER_F,TEACHER_T
0,1,AGUATA,CATHOLIC,CENTRAL SCHOOL ACHINA,10.0,12.0,11.0,12.0,12.0,12.0,...,8,17,17,95,80,175,244,0,6,6
1,2,AGUATA,CATHOLIC,PRIMARY SCHOOL EKE ACHINA,23.0,24.0,11.0,9.0,11.0,10.0,...,10,17,9,93,51,144,232,0,9,9
2,3,AGUATA,CATHOLIC,OBINIKPA SCHOOL ACHINA,3.0,3.0,3.0,2.0,5.0,4.0,...,6,6,5,34,30,64,84,0,2,2
3,4,AGUATA,ANGLICAN,PROGRESSIVE SCHOOL ACHINA,4.0,4.0,5.0,6.0,5.0,2.0,...,4,5,6,44,28,72,98,1,3,4
4,5,AGUATA,CATHOLIC,CENTRAL SCHOOL AGULUEZECHUKWU,34.0,30.0,15.0,18.0,13.0,12.0,...,21,13,10,96,96,192,314,0,7,7

In [34]:
df.fillna(0)
school_df = pd.read_csv("combine_schools.csv")
school_df.head()

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,1,AGUATA HIGH SCH.AGUATA,PUBLIC,Secondary,NaN,NaN
1,13,2,CHRIST THE REDEEMER COLLEGE AMESI,PUBLIC,Secondary,NaN,NaN
2,13,3,COMM SEC. SCH. (BSS) EZINIFITE,PUBLIC,Secondary,NaN,NaN
3,13,4,COMM SEC. SCH. (BSS) IGBOUKWU,PUBLIC,Secondary,NaN,NaN
4,13,5,COMM SEC. SCH. AGULUEZECHUKWU,PUBLIC,Secondary,NaN,NaN

In [35]:
lga_df = pd.read_excel("Anambra_LGAs.xlsx", sheet_name="Sheet1")
lga_df.head()

   lga_id       lga_name     zone
0       1  ONITSHA SOUTH  ONITSHA
1       2   ANAMBRA WEST  OTUOCHA
2       3  IDEMILI SOUTH    OGIDI
3       4    NNEWI SOUTH    NNEWI
4       5            OYI    OGIDI

In [36]:
# Create a new DataFrame
new_df = pd.DataFrame(columns=['school_id', 'timestamp', 'gender', 'population'])
for index, row in df.iterrows():
    lga_id = lga_df.loc[lga_df['lga_name'] == row['LGA'].strip(), 'lga_id'].values[0]
    school_ids = school_df.loc[(school_df['school_name'] == row['SCHOOL'].strip()) & (lga_id == school_df['lga_id']) & (school_df['category'] == 'Primary'), 'school_id'].values
    if(len(school_ids) == 0):
        print(row['SCHOOL'].strip(), "is not in the school_df")
    elif(len(school_ids) > 1):
        print(index, school_df.loc[index, 'school_name'], school_ids)
        
    else: 
        transformed_data = [{
            'school_id': school_ids[0],
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['TEACHER_M'],
        },
        {
            'school_id': school_ids[0],
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['TEACHER_F'],
        }]
        # Append the transformed data to the new DataFrame
        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head()

 is not in the school_df

  school_id   timestamp  gender population
0      2001  01-01-2023    Male          0
1      2001  01-01-2023  Female          6
2      2002  01-01-2023    Male          0
3      2002  01-01-2023  Female          9
4      2003  01-01-2023    Male          0

In [37]:
new_df['population'] = new_df['population'].astype(int)
new_df['timestamp'] = pd.to_datetime(new_df['timestamp'], format='%m-%d-%Y').dt.strftime('%m-%d-%Y')
new_df.head()

  school_id   timestamp  gender  population
0      2001  01-01-2023    Male           0
1      2001  01-01-2023  Female           6
2      2002  01-01-2023    Male           0
3      2002  01-01-2023  Female           9
4      2003  01-01-2023    Male           0

In [39]:
new_df.to_csv("teacher_primary.csv", index=False)
print("Done Printing!")

Done Printing!