In [1]:
import pandas as pd

In [3]:
sheets = ["Sheet1", "Sheet2"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("crops_volume_of_production.xlsx", sheet_name=sheets[index]))

In [5]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[0].head()

   Year       Rice     Cassava      Maize  Vegetables
0  2019  172809.60  1714270.50  205355.50    94923.00
1  2020  176300.59  1748901.06  209503.96    96840.57
2  2021  183495.55  1820275.07  218053.97   100792.71
3  2022  189083.82  1875710.70  224694.71   103862.31
4  2023  194842.28  1932834.59  231537.68   107025.38

In [6]:
columns = ['year', 'crop', 'volume']

new_df = pd.DataFrame(columns=columns)

for index, row in dfs[0].iterrows():
    for col in dfs[0].columns[1:]:
        transformed_data = [{
            'year': row['Year'],
            'crop' : col,
            'volume' : row[col]
        }]
        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_1384\1052604888.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

      year        crop      volume
0   2019.0        Rice   172809.60
1   2019.0     Cassava  1714270.50
2   2019.0       Maize   205355.50
3   2019.0  Vegetables    94923.00
4   2020.0        Rice   176300.59
5   2020.0     Cassava  1748901.06
6   2020.0       Maize   209503.96
7   2020.0  Vegetables    96840.57
8   2021.0        Rice   183495.55
9   2021.0     Cassava  1820275.07
10  2021.0       Maize   218053.97
11  2021.0  Vegetables   100792.71
12  2022.0        Rice   189083.82
13  2022.0     Cassava  1875710.70
14  2022.0       Maize   224694.71
15  2022.0  Vegetables   103862.31
16  2023.0        Rice   194842.28
17  2023.0     Cassava  1932834.59
18  2023.0       Maize   231537.68
19  2023.0  Vegetables   107025.38

In [7]:
new_df['year']=new_df['year'].astype(int)
new_df.head()

   year        crop      volume
0  2019        Rice   172809.60
1  2019     Cassava  1714270.50
2  2019       Maize   205355.50
3  2019  Vegetables    94923.00
4  2020        Rice   176300.59

In [8]:
new_df.to_excel("crop_volume_of_production_transposed.xlsx", index=False)
print("Done!")

Done!