In [1]:
import pandas as pd

In [ ]:
sheets = ["Sheet1"]
file_names = [""]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

   YEAR  EXECUTIVE  HONOURABLE MEMBERS  TOTAL
0  2019          4                   2      6
1  2020         10                   0     10
2  2021          5                   2      7

In [7]:
columns = ['sponsor', 'assembly', 'year', 'no_of_laws']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        for col in df.columns[1:-1]:
            transformed_data = [{
                'sponsor': col.strip(),
                'assembly': '7th',
                'year': row['YEAR'],
                'no_of_laws': row[col],
            }]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

              sponsor assembly  year no_of_laws
0           EXECUTIVE      7th  2019          4
1  HONOURABLE MEMBERS      7th  2019          2
2           EXECUTIVE      7th  2020         10
3  HONOURABLE MEMBERS      7th  2020          0
4           EXECUTIVE      7th  2021          5
5  HONOURABLE MEMBERS      7th  2021          2

In [8]:
new_df['no_of_laws']=new_df['no_of_laws'].astype(int)
new_df.head()

              sponsor assembly  year  no_of_laws
0           EXECUTIVE      7th  2019           4
1  HONOURABLE MEMBERS      7th  2019           2
2           EXECUTIVE      7th  2020          10
3  HONOURABLE MEMBERS      7th  2020           0
4           EXECUTIVE      7th  2021           5

In [9]:
new_df.to_excel("laws_by_sponsors.xlsx", index=False)
print("Done!")

Done!