In [1]:
import pandas as pd

In [2]:
sheets = ["Sheet2"]
file_names = ["job_creation_statistics.xlsx"]
batches = ["Phase 1"]
sessions = ["2022/2023"]

dfs = []
for index, file_name in enumerate(file_names):
    dfs.append(pd.read_excel(file_name, sheet_name="Sheet2"))

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,JOBS,TOTAL NO. OF JOBS CREATED
0,Recruitment into Civil Service,9000
1,SID Digital Skills Empwerment,23000
2,1Youth 2Skills Phase 1 (Direct Jobs through th...,4996
3,Construction Industry,3000
4,Others,5000

In [4]:
columns = ['session', 'batch', 'job', 'no_of_jobs_created']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    for index, row in df.iterrows():
        transformed_data = [{
            'session': sessions[i],
            'batch': batches[i],
            'job': row["JOBS"],
            'no_of_jobs_created': row["TOTAL NO. OF JOBS CREATED"],
        }]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

,session,batch,job,no_of_jobs_created
0,2022/2023,Phase 1,Recruitment into Civil Service,9000
1,2022/2023,Phase 1,SID Digital Skills Empwerment,23000
2,2022/2023,Phase 1,1Youth 2Skills Phase 1 (Direct Jobs through th...,4996
3,2022/2023,Phase 1,Construction Industry,3000
4,2022/2023,Phase 1,Others,5000

In [5]:
new_df['no_of_jobs_created']=new_df['no_of_jobs_created'].astype(int)
new_df.head()

,session,batch,job,no_of_jobs_created
0,2022/2023,Phase 1,Recruitment into Civil Service,9000
1,2022/2023,Phase 1,SID Digital Skills Empwerment,23000
2,2022/2023,Phase 1,1Youth 2Skills Phase 1 (Direct Jobs through th...,4996
3,2022/2023,Phase 1,Construction Industry,3000
4,2022/2023,Phase 1,Others,5000

In [6]:
new_df.to_excel("transposedb/jobs_created.xlsx", index=False)
print("Done!")

Done!