In [37]:
import pandas as pd

In [38]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 178", "Table 179", "Table 180", "Table 181"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

In [39]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,S/N,CMD,JAN,FEB,MAR,APRIL,MAY,JUNE,JULY,AUG,SEPT,OCT,NOV,DEC,TOTAL
0,0.0,OFFENDERS,1431,2696,2254.0,15,681,1959,3234,3049,2417,1510,6,404,19656
1,0.0,OFFENCES,1552,3035,2626.0,16,872,2723,3931,3547,2876,1825,7,484,23494
2,1.0,AMD,1,1,1.0,0,0,1,1,1,5,1,0,1,13
3,2.0,ACS,1,3,16.0,0,2,11,39,15,22,7,0,8,124
4,3.0,CSV,31,63,65.0,1,26,53,93,112,82,49,0,8,583

In [40]:
columns = ['timestamp', 'offenders']
months = {"JAN":"01", "FEB":"02","MAR":"03","APRIL":"04","MAY":"05","JUNE":"06","JULY":"07","AUG":"08","SEPT":"09","OCT":"10","NOV":"11","DEC":"12"}


new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for column in df.columns[2:-1]:
        transformed_data = [{
            'timestamp': str(months[column])+"-01-"+str(year),
            'offenders': df.loc[0, column],
        }]
        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

     timestamp offenders
0   01-01-2019      1134
1   02-01-2019      1592
2   03-01-2019      2235
3   04-01-2019      2679
4   05-01-2019    2648.0
5   06-01-2019      2548
6   07-01-2019      3156
7   08-01-2019      2807
8   09-01-2019      2932
9   10-01-2019      3037
10  11-01-2019      2566
11  12-01-2019      1664
12  01-01-2020      1431
13  02-01-2020      2696
14  03-01-2020    2254.0
15  04-01-2020        15
16  05-01-2020       681
17  06-01-2020      1959
18  07-01-2020      3234
19  08-01-2020      3049
20  09-01-2020      2417
21  10-01-2020      1510

In [41]:
new_df.to_excel("offenders_by_month.xlsx", index=False)
print("Done!")

Done!

In [42]:
columns = ['timestamp', 'offences','count']
months = {"JAN":"01", "FEB":"02","MAR":"03","APRIL":"04","MAY":"05","JUNE":"06","JULY":"07","AUG":"08","SEPT":"09","OCT":"10","NOV":"11","DEC":"12"}


new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for i, row in df.iloc[2:].iterrows():
        for column in df.columns[2:-1]:
            transformed_data = [{
                'timestamp': str(months[column])+"-01-"+str(year),
                'offences': row['CMD'],
                'count': row[column],
            }]
            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

     timestamp offences count
0   01-01-2019      AMD     1
1   02-01-2019      AMD     3
2   03-01-2019      AMD     1
3   04-01-2019      AMD     5
4   05-01-2019      AMD   4.0
5   06-01-2019      AMD     3
6   07-01-2019      AMD     1
7   08-01-2019      AMD     4
8   09-01-2019      AMD     2
9   10-01-2019      AMD     1
10  11-01-2019      AMD     1
11  12-01-2019      AMD     1
12  01-01-2019      ACS     0
13  02-01-2019      ACS     4
14  03-01-2019      ACS     5
15  04-01-2019      ACS     4
16  05-01-2019      ACS   4.0
17  06-01-2019      ACS     0
18  07-01-2019      ACS     2
19  08-01-2019      ACS     2
20  09-01-2019      ACS     7
21  10-01-2019      ACS     9

In [43]:
new_df.to_excel("offences_by_month.xlsx", index=False)
print("Done!")

Done!