In [1]:
import pandas as pd

In [3]:
sheets = ["Table 221"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [5]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[0].head()

,LGA,"WATER TYPE, 2019","WATER TYPE, 2020","WATER TYPE, 2021","WATER TYPE, 2022"
0,AGUATA,0.0,Borehole & surface water,Borehole & surface water,0
1,ANAMBRA EAST,0.0,Borehole & surface water,Borehole & surface water,0
2,ANAMBRA WEST,0.0,0,0,0
3,ANAOCHA,0.0,Borehole,0,0
4,AWKA NORTH,0.0,0,0,0

In [8]:
columns = ['lga_id', 'water_type', 'year']
def count_of_towns_covered(towns):
    towns = towns.replace("and", ',')
    town_count = towns.split(',')
    count = 0
    for elem in town_count:
        if(len(elem.strip()) > 1): count+=1
    return count

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        for col in df.columns[1:]:
            if row[col] == '' or str(row[col]) == "0" or str(row[col]) == "0.0": continue
            for water_type in row[col].strip().split("&"):
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'water_type': water_type.strip(),
                    'year': int(col[-4:]),
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id     water_type  year
0      13       Borehole  2020
1      13  surface water  2020
2      13       Borehole  2021
3      13  surface water  2021
4      18       Borehole  2020
5      18  surface water  2020
6      18       Borehole  2021
7      18  surface water  2021
8       9       Borehole  2020
9      20       Borehole  2020
10      6       Borehole  2021
11      6       Borehole  2022
12     17       Borehole  2021
13     17       Borehole  2022
14      8       Borehole  2021
15      8       Borehole  2022
16      4       Borehole  2020
17     14       Borehole  2020
18     14       Borehole  2021
19     14       Borehole  2022
20      5       Borehole  2020
21      5       Borehole  2021

In [9]:
new_df.to_excel("access_to_safe_water.xlsx", index=False)
print("Done!")

Done!