In [1]:
import pandas as pd

In [3]:
sheets = ["Table 222"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [4]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[0].head()

,LGA,2019-NUMBER OF PEOPLE TRAINED ON WATER MANAGEMENT-MALE,2019-NUMBER OF PEOPLE TRAINED ON WATER MANAGEMENT-FEMALE,2019-NUMBER OF PEOPLE TRAINED ON SANITATION MANAGEMENT-MALE,2019-NUMBER OF PEOPLE TRAINED ON SANITATION MANAGEMENT-FEMALE,2020-NUMBER OF PEOPLE TRAINED ON WATER MANAGEMENT-MALE,2020-NUMBER OF PEOPLE TRAINED ON WATER MANAGEMENT-FEMALE,2020-NUMBER OF PEOPLE TRAINED ON SANITATION MANAGEMENT-MALE,2020-NUMBER OF PEOPLE TRAINED ON SANITATION MANAGEMENT-FEMALE,2021-NUMBER OF PEOPLE TRAINED ON WATER MANAGEMENT-MALE,2021-NUMBER OF PEOPLE TRAINED ON WATER MANAGEMENT-FEMALE,2021-NUMBER OF PEOPLE TRAINED ON SANITATION MANAGEMENT-MALE,2021-NUMBER OF PEOPLE TRAINED ON SANITATION MANAGEMENT-FEMALE
0,AGUATA,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ANAMBRA EAST,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
2,ANAMBRA WEST,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ANAOCHA,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AWKA NORTH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
columns = ['lga_id', 'year', 'gender', 'num_trained_personnel' ]


new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        for col in df.columns[1:]:
            t = col.split('-')
            if 'SANITATION' in t[1]: continue
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'year': t[0].strip(),
                'gender': t[2].strip(),
                'num_trained_personnel': row[col],
            }]

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_1596\4148872584.py:20: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

   lga_id  year  gender  num_trained_personnel
0      13  2019    MALE                    4.0
1      13  2019  FEMALE                    0.0
2      13  2020    MALE                    4.0
3      13  2020  FEMALE                    0.0
4      13  2021    MALE                    0.0
5      13  2021  FEMALE                    0.0
6      18  2019    MALE                    4.0
7      18  2019  FEMALE                    0.0
8      18  2020    MALE                    4.0
9      18  2020  FEMALE                    0.0
10     18  2021    MALE                    3.0
11     18  2021  FEMALE                    0.0
12      2  2019    MALE                    1.0
13      2  2019  FEMALE                    0.0
14      2  2020    MALE                    1.0
15      2  2020  FEMALE                    0.0
16      2  2021    MALE                    0.0
17      2  2021  FEMALE                    0.0
18      9  2019    MALE                    0.0
19      9  2019  FEMALE                    0.0
20      9  2020    MALE                    1.0
21      9  2020  FEMALE                    0.0

In [ ]:
columns = ['lga_id', 'year', 'gender', 'num_trained_personnel' ]


sanitation_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        for col in df.columns[1:]:
            t = col.split('-')
            if 'WATER' in t[1]: continue
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'year': t[0].strip(),
                'gender': t[2].strip(),
                'num_trained_personnel': row[col],
            }]

            sanitation_df = pd.concat([sanitation_df, pd.DataFrame(transformed_data)], ignore_index=True)


sanitation_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_1596\3670430793.py:20: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  sanitation_df = pd.concat([sanitation_df, pd.DataFrame(transformed_data)], ignore_index=True)

   lga_id  year  gender  num_trained_personnel
0      13  2019    MALE                    0.0
1      13  2019  FEMALE                    0.0
2      13  2020    MALE                    0.0
3      13  2020  FEMALE                    0.0
4      13  2021    MALE                    0.0
5      13  2021  FEMALE                    0.0
6      18  2019    MALE                    0.0
7      18  2019  FEMALE                    0.0
8      18  2020    MALE                    0.0
9      18  2020  FEMALE                    0.0
10     18  2021    MALE                    0.0
11     18  2021  FEMALE                    0.0
12      2  2019    MALE                    0.0
13      2  2019  FEMALE                    0.0
14      2  2020    MALE                    0.0
15      2  2020  FEMALE                    0.0
16      2  2021    MALE                    0.0
17      2  2021  FEMALE                    0.0
18      9  2019    MALE                    0.0
19      9  2019  FEMALE                    0.0
20      9  2020    MALE                    0.0
21      9  2020  FEMALE                    0.0

In [7]:
new_df["num_trained_personnel"] = new_df["num_trained_personnel"].astype(int)
sanitation_df["num_trained_personnel"] = sanitation_df["num_trained_personnel"].astype(int)
new_df.head()

  lga_id  year  gender  num_trained_personnel
0     13  2019    MALE                      4
1     13  2019  FEMALE                      0
2     13  2020    MALE                      4
3     13  2020  FEMALE                      0
4     13  2021    MALE                      0

In [8]:
new_df.to_excel("water_management_training.xlsx", index=False)
print("Done!")

sanitation_df.to_excel("sanitation_management_training.xlsx", index=False)
print("Done!")

Done!
Done!