In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 78", "Table 79", "Table 80", "Table 81"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,Children 0-59 months weighed growing well,Children 0-59 months weighed,Children 0-6 months receiving EBF,Children 12-59 months who received deworming medication,Children 6-23 months who received Micronutrient Powder (MNP),Children 6-59 months given Vitamin A,Clients counselled on Infant & Young Child Nutrition (IYCN),"Vitamin A children 12-59 months (200,000 IU)","Vitamin A children 6-11 months (100,000 IU)"
0,AGUATA,9318,15916,10952,2774,24.0,8222,3066,5153,3716
1,ANAMBRA EAST,4389,8731,2814,1264,178.0,1547,1996,2713,1546
2,ANAMBRA WEST,519,1513,179,621,120.0,848,328,556,466
3,ANAOCHA,12882,16810,13172,1100,63.0,2478,333,3374,4049
4,AWKA NORTH,2645,9278,4312,3735,50.0,4108,1262,5203,2609

In [4]:
columns = ['lga_id', 'year', 'data_point', 'value']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["LGA"] == "IDIMILI NORTH"): row["LGA"] = "IDEMILI NORTH"
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])

        else:
            for col in df.columns[1:]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'year': year,
                    'data_point': " ".join(col.replace("\n", " ").split(" ")),
                    'value': row[col]
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id  year                                    data_point  value
0      13  2019   Children (0-59) months weighed growing well    185
1      13  2019                  Children 0-59 months weighed  26751
2      13  2019             Children 0-6 months receiving EBF  11135
3      13  2019  Children 12-59 months who received deworming   3158
4      13  2019  Vitamin A children 12-59 months (200,000 IU)  18096
5      13  2019   Vitamin A children 6-11 months (100,000 IU)   9719
6      18  2019   Children (0-59) months weighed growing well    369
7      18  2019                  Children 0-59 months weighed  14908
8      18  2019             Children 0-6 months receiving EBF   2512
9      18  2019  Children 12-59 months who received deworming   7339
10     18  2019  Vitamin A children 12-59 months (200,000 IU)  11166
11     18  2019   Vitamin A children 6-11 months (100,000 IU)   5299
12      2  2019   Children (0-59) months weighed growing well    233
13      2  2019                  Children 0-59 months weighed   4484
14      2  2019             Children 0-6 months receiving EBF    524
15      2  2019  Children 12-59 months who received deworming   1964
16      2  2019  Vitamin A children 12-59 months (200,000 IU)   2374
17      2  2019   Vitamin A children 6-11 months (100,000 IU)   1796
18      9  2019   Children (0-59) months weighed growing well     43
19      9  2019                  Children 0-59 months weighed  23817
20      9  2019             Children 0-6 months receiving EBF  10149
21      9  2019  Children 12-59 months who received deworming   2516

In [5]:
print("len", len(new_df['data_point'].unique()))
new_df['data_point'].unique()

len 11

array(['Children (0-59) months weighed growing well',
       'Children 0-59 months weighed',
       'Children 0-6 months receiving EBF',
       'Children 12-59 months who received deworming',
       'Vitamin A children 12-59 months (200,000 IU)',
       'Vitamin A children 6-11 months (100,000 IU)',
       'Children 0-59 months weighed growing well',
       'Children 12-59 months who received deworming medication',
       'Children 6-23 months who received Micronutrient Powder (MNP)',
       'Children 6-59 months given Vitamin A',
       'Clients counselled on Infant & Young Child Nutrition (IYCN)'],
      dtype=object)

In [6]:
new_df['value']=new_df['value'].astype(int)
new_df['year']=new_df['year'].astype(int)

new_df.head()

  lga_id  year                                    data_point  value
0     13  2019   Children (0-59) months weighed growing well    185
1     13  2019                  Children 0-59 months weighed  26751
2     13  2019             Children 0-6 months receiving EBF  11135
3     13  2019  Children 12-59 months who received deworming   3158
4     13  2019  Vitamin A children 12-59 months (200,000 IU)  18096

In [7]:
new_df.to_excel("transposed/child_nutrition_data.xlsx", index=False)
print("Finished!")

Finished!