In [1]:
import pandas as pd

In [22]:
# take the last month for both primary and secondary schools
session = "2023/2024"
sch_df = pd.read_csv("combine_schools.csv")
july_state_of_origin = pd.read_csv("../july_state_of_origin.csv")
july_state_of_origin.head(10)
# july_state_of_origin.dtypes

   school_id        state   timestamp  population
0         21         ABIA  07-01-2024           9
1         21      ADAMAWA  07-01-2024           0
2         21    AKWA IBOM  07-01-2024           4
3         21       BAUCHI  07-01-2024           0
4         21      BAYELSA  07-01-2024           1
5         21        BENUE  07-01-2024           4
6         21        BORNO  07-01-2024           0
7         21  CROSS RIVER  07-01-2024           2
8         21        DELTA  07-01-2024           3
9         21       EBONYI  07-01-2024          54

In [25]:
l=[]
for index, row in july_state_of_origin.iterrows():
    l.append(sch_df.loc[sch_df["school_id"]==row["school_id"], "lga_id"].values[0])

july_state_of_origin["lga_id"] = l
july_state_of_origin.head(50)

    school_id        state   timestamp  population  lga_id
0          21         ABIA  07-01-2024           9      13
1          21      ADAMAWA  07-01-2024           0      13
2          21    AKWA IBOM  07-01-2024           4      13
3          21       BAUCHI  07-01-2024           0      13
4          21      BAYELSA  07-01-2024           1      13
5          21        BENUE  07-01-2024           4      13
6          21        BORNO  07-01-2024           0      13
7          21  CROSS RIVER  07-01-2024           2      13
8          21        DELTA  07-01-2024           3      13
9          21       EBONYI  07-01-2024          54      13
10         21          EDO  07-01-2024           0      13
11         21        EKITI  07-01-2024           1      13
12         21        ENUGU  07-01-2024          76      13
13         21        GOMBE  07-01-2024           0      13
14         21          IMO  07-01-2024          22      13
15         21       JIGAWA  07-01-2024           0      13
16         21       KADUNA  07-01-2024           0      13
17         21         KANO  07-01-2024           0      13
18         21      KATSINA  07-01-2024           0      13
19         21        KEBBI  07-01-2024           0      13
20         21         KOGI  07-01-2024           0      13
21         21        KWARA  07-01-2024           0      13
22         21        LAGOS  07-01-2024           0      13
23         21     NASARAWA  07-01-2024           1      13
24         21        NIGER  07-01-2024           0      13
25         21         OGUN  07-01-2024           0      13
26         21         ONDO  07-01-2024           1      13
27         21         OSUN  07-01-2024           0      13
28         21          OYO  07-01-2024           0      13
29         21      PLATEAU  07-01-2024           1      13
30         21       RIVERS  07-01-2024           0      13
31         21       SOKOTO  07-01-2024           0      13
32         21       TARABA  07-01-2024           0      13
33         21         YOBE  07-01-2024           0      13
34         21      ZAMFARA  07-01-2024           0      13
35         21          FCT  07-01-2024           0      13
36         21      FOREIGN  07-01-2024           0      13
37         14         ABIA  07-01-2024          24      13
38         14      ADAMAWA  07-01-2024           0      13
39         14    AKWA IBOM  07-01-2024           3      13
40         14       BAUCHI  07-01-2024           0      13
41         14      BAYELSA  07-01-2024           0      13
42         14        BENUE  07-01-2024           1      13
43         14        BORNO  07-01-2024           0      13
44         14  CROSS RIVER  07-01-2024           4      13
45         14        DELTA  07-01-2024           0      13
46         14       EBONYI  07-01-2024          94      13
47         14          EDO  07-01-2024           1      13
48         14        EKITI  07-01-2024           0      13
49         14        ENUGU  07-01-2024          85      13

In [3]:
sch_df.head()

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,1,AGUATA HIGH SCH.AGUATA,PUBLIC,Secondary,NaN,NaN
1,13,2,CHRIST THE REDEEMER COLLEGE AMESI,PUBLIC,Secondary,NaN,NaN
2,13,3,COMM SEC. SCH. (BSS) EZINIFITE,PUBLIC,Secondary,NaN,NaN
3,13,4,COMM SEC. SCH. (BSS) IGBOUKWU,PUBLIC,Secondary,NaN,NaN
4,13,5,COMM SEC. SCH. AGULUEZECHUKWU,PUBLIC,Secondary,NaN,NaN

In [26]:
import numpy as np
columns = ['lga_id', 'session', 'education_level', 'state', 'population']

new_df = pd.DataFrame(columns=columns)
july_state_of_origin["population"] = july_state_of_origin["population"].astype(int)
new_df["population"] = new_df["population"].astype(int)
for index, row in july_state_of_origin.iterrows():
    lga_id = sch_df.loc[sch_df['school_id'] == row["school_id"], "lga_id"].values[0]
    if(len(new_df[(new_df["lga_id"]==lga_id)&(new_df["state"]==row["state"])])==0):
        filtered_df = july_state_of_origin[(july_state_of_origin["lga_id"]==row["lga_id"]) & (july_state_of_origin["state"]==row["state"])]
        transformed_data = [{
            'lga_id': lga_id,
            'session': session,
            'education_level': "Secondary",
            'state': row['state'],
            'population': np.sum(filtered_df["population"]),
        }]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(50)

   lga_id    session education_level        state  population
0      13  2023/2024       Secondary         ABIA         141
1      13  2023/2024       Secondary      ADAMAWA           5
2      13  2023/2024       Secondary    AKWA IBOM          39
3      13  2023/2024       Secondary       BAUCHI           0
4      13  2023/2024       Secondary      BAYELSA           1
5      13  2023/2024       Secondary        BENUE          25
6      13  2023/2024       Secondary        BORNO           0
7      13  2023/2024       Secondary  CROSS RIVER          18
8      13  2023/2024       Secondary        DELTA          12
9      13  2023/2024       Secondary       EBONYI         617
10     13  2023/2024       Secondary          EDO           3
11     13  2023/2024       Secondary        EKITI           2
12     13  2023/2024       Secondary        ENUGU         519
13     13  2023/2024       Secondary        GOMBE           0
14     13  2023/2024       Secondary          IMO         339
15     13  2023/2024       Secondary       JIGAWA           0
16     13  2023/2024       Secondary       KADUNA           3
17     13  2023/2024       Secondary         KANO           0
18     13  2023/2024       Secondary      KATSINA           0
19     13  2023/2024       Secondary        KEBBI           0
20     13  2023/2024       Secondary         KOGI          10
21     13  2023/2024       Secondary        KWARA           1
22     13  2023/2024       Secondary        LAGOS           0
23     13  2023/2024       Secondary     NASARAWA           2
24     13  2023/2024       Secondary        NIGER           0
25     13  2023/2024       Secondary         OGUN           4
26     13  2023/2024       Secondary         ONDO           5
27     13  2023/2024       Secondary         OSUN           4
28     13  2023/2024       Secondary          OYO           2
29     13  2023/2024       Secondary      PLATEAU           7
30     13  2023/2024       Secondary       RIVERS           3
31     13  2023/2024       Secondary       SOKOTO           0
32     13  2023/2024       Secondary       TARABA           0
33     13  2023/2024       Secondary         YOBE           0
34     13  2023/2024       Secondary      ZAMFARA           0
35     13  2023/2024       Secondary          FCT           0
36     13  2023/2024       Secondary      FOREIGN           3
37      7  2023/2024       Secondary         ABIA          48
38      7  2023/2024       Secondary      ADAMAWA           2
39      7  2023/2024       Secondary    AKWA IBOM          11
40      7  2023/2024       Secondary       BAUCHI           0
41      7  2023/2024       Secondary      BAYELSA           1
42      7  2023/2024       Secondary        BENUE          23
43      7  2023/2024       Secondary        BORNO           0
44      7  2023/2024       Secondary  CROSS RIVER           6
45      7  2023/2024       Secondary        DELTA           4
46      7  2023/2024       Secondary       EBONYI         355
47      7  2023/2024       Secondary          EDO           3
48      7  2023/2024       Secondary        EKITI           0
49      7  2023/2024       Secondary        ENUGU         243

In [27]:
new_df.to_excel("Secondary_State_of_Origin.xlsx", index=False)
print("Done!")

Done!