In [1]:
import pandas as pd

In [23]:
education_levels = ["Secondary", "Primary"]
filenames = ["data/CORE PUBLIC SECONDARY SCHOOLS.xlsx", "data/CORE PUBLIC PRIMARY SCHOOLS.xlsx"]
dfs = []
for index, filename in enumerate(filenames):
    dfs.append(pd.read_excel(filename))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [24]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[0].head()

   S/N          LGEA  M_2021/2022  F_2021/2022  M_ 2024/2025  F_ 2024/2025
0    1        AGUATA         3146         4564          3510          5091
1    2  ANAMBRA EAST         1519         1510          1694          1685
2    3  ANAMBRA WEST          456          520           509           580
3    4       ANAOCHA         2018         2790          2251          3112
4    5    AWKA NORTH         1430         1587          1595          1770

In [25]:
columns = ['lga_id', 'session', 'education_level', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGEA"], "lga_id"].values) == 0):
            print(row["LGEA"])
        # print(row)
        else:
            for col in df.columns[2:]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGEA"], "lga_id"].values[0],
                    'session': col.strip().split('_')[1],
                    'education_level': education_levels[i],
                    'gender': "Male" if col.strip().split('_')[0] == 'M' else "FEMALE",
                    'population': row[col],
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id     session education_level  gender population
0      13   2021/2022       Secondary    Male       3146
1      13   2021/2022       Secondary  FEMALE       4564
2      13   2024/2025       Secondary    Male       3510
3      13   2024/2025       Secondary  FEMALE       5091
4      18   2021/2022       Secondary    Male       1519
5      18   2021/2022       Secondary  FEMALE       1510
6      18   2024/2025       Secondary    Male       1694
7      18   2024/2025       Secondary  FEMALE       1685
8       2   2021/2022       Secondary    Male        456
9       2   2021/2022       Secondary  FEMALE        520
10      2   2024/2025       Secondary    Male        509
11      2   2024/2025       Secondary  FEMALE        580
12      9   2021/2022       Secondary    Male       2018
13      9   2021/2022       Secondary  FEMALE       2790
14      9   2024/2025       Secondary    Male       2251
15      9   2024/2025       Secondary  FEMALE       3112
16     15   2021/2022       Secondary    Male       1430
17     15   2021/2022       Secondary  FEMALE       1587
18     15   2024/2025       Secondary    Male       1595
19     15   2024/2025       Secondary  FEMALE       1770
20     20   2021/2022       Secondary    Male       5268
21     20   2021/2022       Secondary  FEMALE       5693

In [26]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

  lga_id     session education_level  gender  population
0     13   2021/2022       Secondary    Male        3146
1     13   2021/2022       Secondary  FEMALE        4564
2     13   2024/2025       Secondary    Male        3510
3     13   2024/2025       Secondary  FEMALE        5091
4     18   2021/2022       Secondary    Male        1519

In [27]:
new_df.to_excel("transposedb/core_public_schools_student_population.xlsx", index=False)
print("Done!")

Done!