In [3]:
import pandas as pd

In [4]:
july_df = pd.read_csv("../july_state_of_origin.csv")
july_df.head()

   school_id      state   timestamp  population
0         21       ABIA  07-01-2024           9
1         21    ADAMAWA  07-01-2024           0
2         21  AKWA IBOM  07-01-2024           4
3         21     BAUCHI  07-01-2024           0
4         21    BAYELSA  07-01-2024           1

In [6]:
aguata_df = july_df[july_df["state"]=="FOREIGN"]
aguata_df.head(20)

     school_id    state   timestamp  population
36          21  FOREIGN  07-01-2024           0
73          14  FOREIGN  07-01-2024           0
110         12  FOREIGN  07-01-2024           0
147          1  FOREIGN  07-01-2024           0
184         15  FOREIGN  07-01-2024           0
221         19  FOREIGN  07-01-2024           1
258         11  FOREIGN  07-01-2024           0
295         17  FOREIGN  07-01-2024           0
332          8  FOREIGN  07-01-2024           2
369         20  FOREIGN  07-01-2024           0
406         16  FOREIGN  07-01-2024           0
443         18  FOREIGN  07-01-2024           0
480          9  FOREIGN  07-01-2024           0
517         10  FOREIGN  07-01-2024           0
554          7  FOREIGN  07-01-2024           0
591          5  FOREIGN  07-01-2024           0
628          6  FOREIGN  07-01-2024           0
665          2  FOREIGN  07-01-2024           0
702          4  FOREIGN  07-01-2024           0
739          3  FOREIGN  07-01-2024           0

In [7]:
school_df=pd.read_csv("combine_schools.csv")
school_df.head()

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,1,AGUATA HIGH SCH.AGUATA,PUBLIC,Secondary,NaN,NaN
1,13,2,CHRIST THE REDEEMER COLLEGE AMESI,PUBLIC,Secondary,NaN,NaN
2,13,3,COMM SEC. SCH. (BSS) EZINIFITE,PUBLIC,Secondary,NaN,NaN
3,13,4,COMM SEC. SCH. (BSS) IGBOUKWU,PUBLIC,Secondary,NaN,NaN
4,13,5,COMM SEC. SCH. AGULUEZECHUKWU,PUBLIC,Secondary,NaN,NaN

In [9]:
l=[]
for index, row in july_df.iterrows():
    l.append(school_df.loc[school_df["school_id"]==row["school_id"], "lga_id"].values[0])

july_df["lga_id"] = l
july_df.head(50)

    school_id        state   timestamp  population  lga_id
0          21         ABIA  07-01-2024           9      13
1          21      ADAMAWA  07-01-2024           0      13
2          21    AKWA IBOM  07-01-2024           4      13
3          21       BAUCHI  07-01-2024           0      13
4          21      BAYELSA  07-01-2024           1      13
5          21        BENUE  07-01-2024           4      13
6          21        BORNO  07-01-2024           0      13
7          21  CROSS RIVER  07-01-2024           2      13
8          21        DELTA  07-01-2024           3      13
9          21       EBONYI  07-01-2024          54      13
10         21          EDO  07-01-2024           0      13
11         21        EKITI  07-01-2024           1      13
12         21        ENUGU  07-01-2024          76      13
13         21        GOMBE  07-01-2024           0      13
14         21          IMO  07-01-2024          22      13
15         21       JIGAWA  07-01-2024           0      13
16         21       KADUNA  07-01-2024           0      13
17         21         KANO  07-01-2024           0      13
18         21      KATSINA  07-01-2024           0      13
19         21        KEBBI  07-01-2024           0      13
20         21         KOGI  07-01-2024           0      13
21         21        KWARA  07-01-2024           0      13
22         21        LAGOS  07-01-2024           0      13
23         21     NASARAWA  07-01-2024           1      13
24         21        NIGER  07-01-2024           0      13
25         21         OGUN  07-01-2024           0      13
26         21         ONDO  07-01-2024           1      13
27         21         OSUN  07-01-2024           0      13
28         21          OYO  07-01-2024           0      13
29         21      PLATEAU  07-01-2024           1      13
30         21       RIVERS  07-01-2024           0      13
31         21       SOKOTO  07-01-2024           0      13
32         21       TARABA  07-01-2024           0      13
33         21         YOBE  07-01-2024           0      13
34         21      ZAMFARA  07-01-2024           0      13
35         21          FCT  07-01-2024           0      13
36         21      FOREIGN  07-01-2024           0      13
37         14         ABIA  07-01-2024          24      13
38         14      ADAMAWA  07-01-2024           0      13
39         14    AKWA IBOM  07-01-2024           3      13
40         14       BAUCHI  07-01-2024           0      13
41         14      BAYELSA  07-01-2024           0      13
42         14        BENUE  07-01-2024           1      13
43         14        BORNO  07-01-2024           0      13
44         14  CROSS RIVER  07-01-2024           4      13
45         14        DELTA  07-01-2024           0      13
46         14       EBONYI  07-01-2024          94      13
47         14          EDO  07-01-2024           1      13
48         14        EKITI  07-01-2024           0      13
49         14        ENUGU  07-01-2024          85      13

In [24]:
import numpy as np
for i in range(10,22):
    filtered_df = july_df[(july_df["lga_id"]==i) & (july_df["state"]=="FOREIGN")]
    print(i, len(filtered_df))
    print(np.sum(filtered_df["population"]))

10 8
4
11 11
2
12 8
3
13 21
3
14 16
10
15 10
0
16 17
1
17 8
5
18 11
0
19 10
0
20 19
8
21 15
0

In [25]:
secondary_df = pd.read_excel("Secondary_State_of_Origin.xlsx")
secondary_df.head()

   lga_id    session education_level      state  population
0      13  2023/2024       Secondary       ABIA           9
1      13  2023/2024       Secondary    ADAMAWA           0
2      13  2023/2024       Secondary  AKWA IBOM           4
3      13  2023/2024       Secondary     BAUCHI           0
4      13  2023/2024       Secondary    BAYELSA           1

In [28]:
# sec_filtered_df = secondary_df[secondary_df[""]]
for i in range(13,22):
    filtered_df = secondary_df[(secondary_df["lga_id"]==i) & (secondary_df["state"]=="FOREIGN")]
    print(i, len(filtered_df))
    print(np.sum(filtered_df["population"]))

13 1
0
14 1
0
15 1
0
16 1
0
17 1
3
18 1
0
19 1
0
20 1
0
21 1
0